[package]
name = "sensors"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]
path = "src/sensors/lib.rs"

[lints.rust]
future_incompatible = { level = "warn", priority = -1 }
nonstandard_style = { level = "warn", priority = -1 }
unused = { level = "warn", priority = -1 }
rust_2018_idioms = { level = "warn", priority = -1 }
keyword_idents = { level = "warn", priority = -1 }
rust_2018_compatibility = { level = "warn", priority = -1 }
let_underscore = { level = "warn", priority = -1 }
deprecated_safe = { level = "warn", priority = -1 }
refining_impl_trait = { level = "warn", priority = -1 }
missing_docs = "warn"
unused_qualifications = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
single_use_lifetimes = "warn"
unused_lifetimes = "warn"
unit_bindings = "warn"
unused_import_braces = "warn"
variant_size_differences = "warn"
non_ascii_idents = "warn"
unused_crate_dependencies = "warn"
meta_variable_misuse = "warn"
macro_use_extern_crate = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
unnameable_types = "warn"
unstable_features = "warn"
deprecated_in_future = "warn"
ffi_unwind_calls = "warn"
ambiguous_negative_literals = "warn"
closure_returning_async_block = "warn"
impl_trait_redundant_captures = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
undocumented_unsafe_blocks = "warn"
multiple_unsafe_ops_per_block = "warn"
as_conversions = "warn"
default_numeric_fallback = "warn"
arithmetic_side_effects = "warn"
indexing_slicing = "warn"
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
dbg_macro = "warn"
mem_forget = "warn"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
pub_without_shorthand = "warn"
str_to_string = "warn"
string_to_string = "warn"
lossy_float_literal = "warn"
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"
float_arithmetic = "warn"
float_cmp_const = "warn"
integer_division = "warn"
modulo_arithmetic = "warn"
host_endian_bytes = "warn"
fn_to_numeric_cast_any = "warn"
infinite_loop = "warn"
unimplemented = "warn"
unreachable = "warn"
unwrap_in_result = "warn"
panic_in_result_fn = "warn"
missing_assert_message = "warn"
let_underscore_must_use = "warn"
map_err_ignore = "warn"
mixed_read_write_in_expression = "warn"
string_slice = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
wildcard_enum_match_arm = "warn"
try_err = "warn"
empty_drop = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
if_then_some_else_none = "warn"
impl_trait_in_params = "warn"
multiple_inherent_impl = "warn"
partial_pub_fields = "warn"
redundant_type_annotations = "warn"
ref_patterns = "warn"
same_name_method = "warn"
semicolon_outside_block = "warn"
single_char_lifetime_names = "warn"
tests_outside_test_module = "warn"
unneeded_field_pattern = "warn"
unseparated_literal_suffix = "warn"
use_debug = "warn"
renamed_function_params = "warn"
unused_trait_names = "warn"
pub_use = "warn"
exit = "warn"
deref_by_slicing = "warn"
decimal_literal_representation = "warn"
error_impl_error = "warn"
multiple_crate_versions = "warn"
negative_feature_names = "warn"
redundant_feature_names = "warn"
wildcard_dependencies = "warn"
as_pointer_underscore = "warn"
as_underscore = "warn"
assertions_on_result_states = "warn"
cfg_not_test = "warn"
default_union_representation = "warn"
else_if_without_else = "warn"
filetype_is_file = "warn"
get_unwrap = "warn"
let_underscore_untyped = "warn"
missing_asserts_for_indexing = "warn"
mutex_atomic = "warn"
mutex_integer = "warn"
non_ascii_literal = "warn"
non_zero_suggestions = "warn"
pointer_format = "warn"
precedence_bits = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
clone_on_ref_ptr = "warn"
rest_pat_in_fully_bound_structs = "warn"
shadow_same = "warn"
shadow_reuse = "warn"
shadow_unrelated = "warn"
string_add = "warn"
string_lit_chars_any = "warn"
suspicious_xor_used_as_pow = "warn"
unnecessary_self_imports = "warn"
unused_result_ok = "warn"
needless_raw_strings = "warn"
return_and_then = "warn"
map_with_unused_argument_over_ranges = "warn"
large_include_file = "warn"
doc_include_without_cfg = "warn"
field_scoped_visibility_modifiers = "warn"
iter_over_hash_type = "warn"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
