; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; NOTE: Platform.io does not support inline comments
[platformio]
; switch to src_dir and default_env to flash different board and projects
default_envs = esp32-p4
src_dir = ${PROJECT_DIR}/src_master
;src_dir = ${PROJECT_DIR}/src_node


[env]
platform = espressif32
framework = espidf
monitor_speed = 115200

;[env:myrelease]
;build_type = release
;targets = upload, monitor

[env:esp32-p4]
board = esp32-p4


[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
; change microcontroller
board_build.mcu = esp32c3



