; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Node]
platform = espressif32
board = esp32-c3-devkitm-1
monitor_speed = 115200

board_build.mcu = esp32c3
framework = espidf

[env:NodeSerialTest]
extends = env:Node
build_flags =
    -D NODE_SERIAL_TEST_RPM_GPIO=3
    -D NODE_ENCODER_TEST_ONLY=1
    -D NODE_SERIAL_DEBUG_SAMPLES=1
    -D NODE_START_ACTIVE_ON_BOOT=1
    -D NODE_CAN_TX_GPIO=4
    -D NODE_CAN_RX_GPIO=5
    -D NODE_SERIAL_TEST_ENCODER_GPIO_A=6
    -D NODE_SERIAL_TEST_ENCODER_GPIO_B=7
